-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Tempo de geração: 03/10/2023 às 17:54
-- Versão do servidor: 10.3.39-MariaDB-cll-lve
-- Versão do PHP: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `ybxvukgr_read_book`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `admins`
--

CREATE TABLE `admins` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `idUsuario` bigint(20) UNSIGNED NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Despejando dados para a tabela `admins`
--

INSERT INTO `admins` (`id`, `idUsuario`, `created_at`, `updated_at`) VALUES
(1, 1, '2023-08-02 00:36:07', '2023-08-02 00:36:07');

-- --------------------------------------------------------

--
-- Estrutura para tabela `livros`
--

CREATE TABLE `livros` (
  `id_livro` bigint(20) UNSIGNED NOT NULL,
  `id_usuario` bigint(20) UNSIGNED NOT NULL,
  `img_livro` varchar(255) DEFAULT NULL,
  `nome_livro` varchar(255) NOT NULL,
  `descricao_livro` text DEFAULT NULL,
  `lido` varchar(255) NOT NULL,
  `tempo_lido` varchar(255) NOT NULL,
  `paginas_lidas` varchar(255) NOT NULL,
  `total_paginas` varchar(255) DEFAULT NULL,
  `data_inicio` varchar(255) DEFAULT NULL,
  `data_termino` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Despejando dados para a tabela `livros`
--

INSERT INTO `livros` (`id_livro`, `id_usuario`, `img_livro`, `nome_livro`, `descricao_livro`, `lido`, `tempo_lido`, `paginas_lidas`, `total_paginas`, `data_inicio`, `data_termino`, `created_at`, `updated_at`) VALUES
(2, 1, '../img_livros/bibioteca_da_meia_noite.jpg', 'A Biblioteca da Meia-Noite', 'Aos 35 anos, Nora Seed é uma mulher cheia de talentos e poucas conquistas. Arrependida das escolhas que fez no passado, ela vive se perguntando o que poderia ter acontecido caso tivesse vivido de maneira diferente. Após ser demitida e seu gato ser atropelado, Nora vê pouco sentido em sua existência e decide colocar um ponto final em tudo. Porém, quando se vê na Biblioteca da Meia-Noite, Nora ganha uma oportunidade única de viver todas as vidas que poderia ter vivido.\r\n\r\nNeste lugar entre a vida e a morte, e graças à ajuda de uma velha amiga, Nora pode, finalmente, se mudar para a Austrália, reatar relacionamentos antigos – ou começar outros –, ser uma estrela do rock, uma glaciologista, uma nadadora olímpica... enfim, as opções são infinitas. Mas será que alguma dessas outras vidas é realmente melhor do que a que ela já tem?\r\n\r\nEm A Biblioteca da Meia-Noite, Nora Seed se vê exatamente na situação pela qual todos gostaríamos de poder passar: voltar no tempo e desfazer algo de que nos arrependemos. Diante dessa possibilidade, Nora faz um mergulho interior viajando pelos livros da Biblioteca da Meia-Noite até entender o que é verdadeiramente importante na vida e o que faz, de fato, com que ela valha a pena ser vivida.', 'sim', '5 dias', '308', '308', '10/05/2023', '15/05/2023', '2023-06-03 07:29:59', '2023-06-07 02:58:35'),
(3, 3, 'http://books.google.com/books/content?id=taFjEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api', 'Antes que o café esfrie', 'Quem você gostaria de encontrar, uma única e última vez, se fosse possível viajar no tempo? Em uma ruazinha estreita e silenciosa de Tóquio, num subsolo, existe um estabelecimento que, há mais de 100 anos, serve um café cuidadosamente preparado. Graças a uma lenda urbana, o local recebe diversos frequentadores que esperam ansiosamente para viver uma experiência única: fazer uma viagem no tempo. Aqueles que retornam ao passado devem estar cientes dos riscos e também das regras, já que a jornada exige que o cliente se sente numa cadeira específica e reencontre somente pessoas que já tenham visitado o estabelecimento. Mesmo assim, quatro personagens aproveitam a oportunidade para tentar resolver dramas do passado. A experiência é imperdível, mas o tempo é curto. Mais precisamente, até o café esfriar. Antes que o Café Esfrie é um romance do autor japonês Toshikazu Kawaguchi e best‐ seller do USA Today e do Times de Londres. Alcançou o 1o lugar na lista de mais vendidos (ficção literária internacional) da rede de livrarias Waterstones, no Reino Unido, e foi o romance traduzido mais vendido de 2020. No Japão, ultrapassou a incrível marca de 1 milhão de livros vendidos e segue fazendo sucesso em outros países como Taiwan, França e Itália.', 'não', '0 dias', '0', '208', '', NULL, '2023-06-03 07:47:42', '2023-06-06 06:24:16'),
(4, 1, '../img_livros/todas_as_suas_imperfeicoes.jpg', 'Todas as suas (im)perfeições', 'Uma história de amor perfeita é suficiente para manter vivo o casamento entre duas pessoas imperfeitas? Quando a dança começa, a sincronia é perfeita, os passos seguem o ritmo, as mãos não se soltam, os olhos jamais se deixam. Mas a música pode acabar a qualquer momento... É possível valsar no silêncio? Quinn e Graham se conhecem no pior dia de suas vidas; ela chega mais cedo de uma viagem para surpreender o noivo, ele testemunha a traição da namorada. E é assim que ambos acabam no corredor de um prédio, trocando confidências, biscoitos da sorte e palavras de conforto. Fim da dança... se o destino não tivesse outros planos para os dois. Meses mais tarde, os acordes tocam para o casal mais uma vez e eles se reencontram. Graham está convencido de que são almas gêmeas. Quinn jamais se sentiu dessa forma antes. A intensidade do sentimento os assusta, mas, ainda assim, eles mergulham de cabeça. O casamento é tudo o que sonhavam, a parceria perfeita. Mesmo nos momentos difíceis, sabem que podem contar com o outro. Nenhum deles desiste do amor que sentem. Até que a primeira nota dissonante abala a sinfonia do casal. Quinn parece estar disposta a trocar tudo o que é pela única coisa que não consegue ser: mãe. A luta do casal por um filho arrisca os alicerces da relação. Quinn não pode engravidar. Graham não é um candidato para adoção por conta de um erro do passado. O impasse os deixa parados no salão, no silêncio. A orquestra está em suspenso. Os dois parecem surdos para a música do amor de ambos. Será que é possível voltar a ouvir? A dançar? Ou será que vão descobrir a mais triste verdade de todas... que, às vezes, apenas amar não é o bastante?', 'sim', '15 dias', '304', '304', '19/05/2023', '03/06/2023', '2023-06-04 03:49:04', '2023-06-05 06:13:00'),
(13, 3, NULL, 'O poder do silêncio', 'Meu teste', 'não', '0 dias', '0', '200', '', NULL, '2023-06-05 06:31:56', '2023-06-06 06:57:08'),
(14, 1, '../img_livros/eu_e_esse_meu_coracao.jpg', 'Eu e esse meu coração', 'Leah MacKenzie, de 17 anos, não tem coração. O que a mantém viva é um coração artificial que ela carrega dentro de uma mochila. Com seu tipo sanguíneo raro, um transplante é como um sonho distante. Conformada, ela tenta se esquecer de que está com os dias contados, criando uma lista de “coisas para fazer antes de morrer”. De repente, Leah recebe uma segunda chance: há um coração disponível! O problema é quando ela descobre que o doador é um garoto da sua escola – e que supostamente se matou! Matt, o irmão gêmeo do doador, se recusa a acreditar que Eric se suicidou. Quando Leah o procura, eles descobrem que ambos têm sonhos semelhantes que podem ter pistas do que realmente aconteceu a Eric. Enquanto tentam desvendar esse mistério, Matt e Leah se apaixonam e não querem correr o risco de perder um ao outro. Mas nem a vida nem um coração transplantado vem com garantias. Quem diria que viver exige mais coragem do que morrer?', 'sim', '19 dias', '426', '426', '05/06/2023', '24/06/2023', '2023-06-06 05:15:37', '2023-07-28 04:03:00'),
(15, 3, NULL, 'qw qwqwq wqwqw qw qwqw', 'Terror', 'sim', '0 dias', '0', '200', '06/06/2023', '06/06/2023', '2023-06-07 02:50:19', '2023-06-07 02:54:35'),
(16, 5, 'http://books.google.com/books/content?id=taFjEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api', 'Antes que o café esfrie', 'Quem você gostaria de encontrar, uma única e última vez, se fosse possível viajar no tempo? Em uma ruazinha estreita e silenciosa de Tóquio, num subsolo, existe um estabelecimento que, há mais de 100 anos, serve um café cuidadosamente preparado. Graças a uma lenda urbana, o local recebe diversos frequentadores que esperam ansiosamente para viver uma experiência única: fazer uma viagem no tempo. Aqueles que retornam ao passado devem estar cientes dos riscos e também das regras, já que a jornada exige que o cliente se sente numa cadeira específica e reencontre somente pessoas que já tenham visitado o estabelecimento. Mesmo assim, quatro personagens aproveitam a oportunidade para tentar resolver dramas do passado. A experiência é imperdível, mas o tempo é curto. Mais precisamente, até o café esfriar. Antes que o Café Esfrie é um romance do autor japonês Toshikazu Kawaguchi e best‐ seller do USA Today e do Times de Londres. Alcançou o 1o lugar na lista de mais vendidos (ficção literária internacional) da rede de livrarias Waterstones, no Reino Unido, e foi o romance traduzido mais vendido de 2020. No Japão, ultrapassou a incrível marca de 1 milhão de livros vendidos e segue fazendo sucesso em outros países como Taiwan, França e Itália.', 'sim', '10 dias', '208', '208', '06/06/2023', '16/06/2023', '2023-06-07 03:02:18', '2023-06-07 03:02:46'),
(17, 7, 'http://books.google.com/books/content?id=kmHOsLdnP9oC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api', 'Anne Frank Remembered', 'She found the diary and brought the world a message of love and hope. It seems as if we are never far from Miep\'s thoughts....Yours, Anne For the millions moved by Anne Frank: The Diary of a Young Girl,here at last is Miep\'s own astonishing story. For more than two years, Miep Gies and her husband helped hide the Franks from the Nazis. Like thousands of unsung heroes of the Holocaust, they risked their lives each day to bring food, news, and emotional support to the victims. From her own remarkable childhood as a World War I refugee to the moment she places a small, red-orange, checkered diary -- Anne\'s legacy -- in Otto Frank\'s hands, Miep Gies remembers her days with simple honesty and shattering clarity. Each page rings with courage and heartbreaking beauty.', 'não', '0 dias', '0', '320', '20/06/2023', NULL, '2023-06-20 21:19:32', '2023-06-20 21:19:32'),
(18, 1, '../img_livros/e_assim_que_acaba.jpg', 'É Assim que Acaba', 'Da autora das séries Slammed e Hopeless. Um romance sobre as escolhas corretas nas situações mais difíceis. As coisas não foram sempre fáceis para Lily, mas isso nunca a impediu de conquistar a vida tão sonhada. Ela percorreu um longo caminho desde a infância, em uma cidadezinha no Maine: se formou em marketing, mudou para Boston e abriu a própria loja. Então, quando se sente atraída por um lindo neurocirurgião chamado Ryle Kincaid, tudo parece perfeito demais para ser verdade. Ryle é confiante, teimoso, talvez até um pouco arrogante e se sente atraído por Lily. Porém, sua grande aversão a relacionamentos é perturbadora. Além de estar sobrecarregada com as questões sobre seu novo relacionamento, Lily não consegue tirar Atlas Corrigan da cabeça — seu primeiro amor e a ligação com o passado que ela deixou para trás. Ele era seu protetor, alguém com quem tinha grande afinidade. Quando Atlas reaparece de repente, tudo que Lily construiu com Ryle fica em risco. Com um livro ousado e extremamente pessoal, Colleen Hoover conta uma história arrasadora, mas também inovadora, que não tem medo de discutir temas como abuso e violência doméstica. Uma narrativa inesquecível sobre um amor que custa caro demais.', 'sim', '10 dias', '374', '374', '26/06/23', '06/07/23', '2023-06-25 23:49:04', '2023-07-06 17:03:38'),
(19, 1, '../img_livros/e_assim_que_comeca.jpg', 'Isto Começa Aqui', 'A continuação da história de Lily e Atlas na imperdível sequela de Isto Acaba Aqui, um dos maiores fenómenos editoriais dos últimos tempos Será assim tão simples começar de novo? Depois do seu reencontro inesperado, Lily e Atlas não conseguem parar de pensar um no outro nem em tudo aquilo por que passaram. Mas uma nova aproximação entre eles poderá não ser tão simples como parece. Lily tem de pensar no bem-estar da filha e na reação de Ryle a uma eventual relação com Atlas. Atlas também está ciente das dificuldades. Sabe que Ryle não irá aceitar facilmente a sua presença na vida da ex-mulher e da filha e não tem dúvidas de que os problemas de comportamento dele não terminaram com o fim do casamento. Terão Lily e Atlas força suficiente para enfrentar todos os obstáculos que irão surgir pelo caminho?', 'sim', '20 dias', '347', '347', '06/07/2023', '26/07/2023', '2023-07-06 16:48:36', '2023-07-28 19:46:32'),
(20, 1, '../img_livros/72.png', 'A Garota do Lago', 'Summit Lake, uma pequena cidade entre montanhas, é esse tipo de lugar, bucólico e com encantadoras casas dispostas à beira de um longo trecho de água intocada.Duas semanas atrás, a estudante de direito Becca Eckersley foi brutalmente assassinada em uma dessas casas. Filha de um poderoso advogado, Becca estava no auge de sua vida. Atraída instintivamente pela notícia, a repórter Kelsey Castle vai até a cidade para investigar o caso. ...E LOGO SE ESTABELECE UMA CONEXÃO ÍNTIMA QUANDO UM VIVO CAMINHA NAS MESMAS PEGADAS DOS MORTOS...E enquanto descobre sobre as amizades de Becca, sua vida amorosa e os segredos que ela guardava, a repórter fica cada vez mais convencida de que a verdade sobre o que aconteceu com Becca pode ser a chave para superar as marcas sombrias de seu próprio passado.', 'sim', '13 dias', '199', '199', '27/07/23', '09/08/2023', '2023-07-28 05:58:43', '2023-08-10 15:53:45'),
(24, 8, '../img_livros/24.jpg', 'A Culpa é das Estrelas', 'Apesar do milagre da medicina que fez diminuir o tumor que a atacara há alguns anos, Hazel nunca tinha conhecido outra situação que não a de doente terminal, sendo o capítulo final da sua vida parte integrante do seu diagnóstico. Mas com a chegada repentina ao Grupo de Apoio dos Miúdos com Cancro de uma atraente reviravolta de seu nome Augustus Waters, a história de Hazel vê-se agora prestes a ser completamente rescrita.Perspicaz, arrojado, irreverente e cru, A Culpa é das Estrelas é a obra mais ambiciosa e comovente que o premiado autor John Green nos apresentou até hoje, explorando de maneira brilhante a aventura divertida, empolgante e trágica que é estar-se vivo e apaixonado.John Green é autor de vários bestsellers do The New York Times. Recebeu o Michael L. Printz Award e o Edgar Award. Foi por duas vezes finalista do L. A. Times Book Prize. Os seus livros foram traduzidos em mais de vinte línguas. John é também o co-criador, com o seu irmão Hank, do vlogbrothers, uma série de vídeos on-line que já foram visionados mais de 200 milhões de vezes.\"John Green não é apenas um autor. É uma vedeta da multimédia que se apresenta perante auditórios de mil lugares de fãs aos gritos.\" Los Angeles Times', 'sim', '24 dias', '255', '255', '10/11/2022', '06/12/2022', '2023-08-02 03:51:49', '2023-10-03 23:18:47'),
(25, 8, '../img_livros/a_cinco_passos_de_voce2.png', 'A cinco passos de você', 'Agora uma superprodução cinematográfica estrelada por Cole Sprouse, de “Riverdale”. 21 de março nos cinemas. Stella Grant gosta de controle. Ela parece uma adolescente típica, mas em sua rotina há listas de tarefas e inúmeros remédios que deve tomar para controlar a fibrose cística, doença crônica que impede que seus pulmões funcionem como deveriam. Para conseguir um transplante, ela precisa seguir seu tratamento e eliminar qualquer chance de infecção, o que significa ficar a pelo menos seis passos de outros pacientes com a doença – sem exceção. Will Newman não dá a mínima para o novo tratamento experimental para o qual foi selecionado. Prestes a completar dezoito anos, ele mal pode esperar para finalmente se livrar das máquinas e hospitais, usando o pouco de vida que ainda lhe resta para conhecer o mundo. Stella e Will são muito diferentes. Ao mesmo tempo, sua doença não é a única coisa que os une. Eles não podem se aproximar, mas, conforme sua conexão aumenta, os seis passos entre eles passam a ser insuportáveis. E se pudessem quebrar as regras? Cinco passos são tão perigosos quanto perder um grande amor? “E se você se apaixonasse mas não pudesse tocar seu amado? A cinco passos de você estreou na lista de mais vendidos do New York Times apenas uma semana após seu lançamento.” – PUBLISHERS WEEKLY “A cinco passos de você o fará chorar e provocará um forte déjà-vu nos fãs de A culpa é das estrelas. Essa é uma história inspiradora sobre pessoas que fazem cada momento contar – e sobre o poder transcendental do amor.” – COSMOPOLITAN', 'Sim', '10 dias', '288', '288', '06/12/2022', '17/12/2022', '2023-08-02 04:09:07', '2023-08-02 04:10:15'),
(26, 8, '../img_livros/love_e_gelato.png', 'Love & Gelato', '\"After her mother dies, Lina travels to Italy where she discovers her mothers\'s journal and sets off on an adventure to unearth her mother\'s secrets\"--', 'Sim', '4 dias', '416', '416', '19/12/2022', '22/12/2022', '2023-08-02 04:11:13', '2023-08-02 13:13:22'),
(27, 8, '../img_livros/eu_e_esse_meu_coracao.jpg', 'Eu e esse meu coração', 'Leah MacKenzie, de 17 anos, não tem coração. O que a mantém viva é um coração artificial que ela carrega dentro de uma mochila. Com seu tipo sanguíneo raro, um transplante é como um sonho distante. Conformada, ela tenta se esquecer de que está com os dias contados, criando uma lista de “coisas para fazer antes de morrer”. De repente, Leah recebe uma segunda chance: há um coração disponível! O problema é quando ela descobre que o doador é um garoto da sua escola – e que supostamente se matou! Matt, o irmão gêmeo do doador, se recusa a acreditar que Eric se suicidou. Quando Leah o procura, eles descobrem que ambos têm sonhos semelhantes que podem ter pistas do que realmente aconteceu a Eric. Enquanto tentam desvendar esse mistério, Matt e Leah se apaixonam e não querem correr o risco de perder um ao outro. Mas nem a vida nem um coração transplantado vem com garantias. Quem diria que viver exige mais coragem do que morrer?', 'Sim', '6 dias', '426', '426', '28/12/2022', '02/01/2022', '2023-08-02 04:13:08', '2023-08-02 04:14:49'),
(28, 8, '../img_livros/todas_as_suas_imperfeicoes.jpg', 'Todas as suas (im)perfeições', 'Uma história de amor perfeita é suficiente para manter vivo o casamento entre duas pessoas imperfeitas? Quando a dança começa, a sincronia é perfeita, os passos seguem o ritmo, as mãos não se soltam, os olhos jamais se deixam. Mas a música pode acabar a qualquer momento... É possível valsar no silêncio? Quinn e Graham se conhecem no pior dia de suas vidas; ela chega mais cedo de uma viagem para surpreender o noivo, ele testemunha a traição da namorada. E é assim que ambos acabam no corredor de um prédio, trocando confidências, biscoitos da sorte e palavras de conforto. Fim da dança... se o destino não tivesse outros planos para os dois. Meses mais tarde, os acordes tocam para o casal mais uma vez e eles se reencontram. Graham está convencido de que são almas gêmeas. Quinn jamais se sentiu dessa forma antes. A intensidade do sentimento os assusta, mas, ainda assim, eles mergulham de cabeça. O casamento é tudo o que sonhavam, a parceria perfeita. Mesmo nos momentos difíceis, sabem que podem contar com o outro. Nenhum deles desiste do amor que sentem. Até que a primeira nota dissonante abala a sinfonia do casal. Quinn parece estar disposta a trocar tudo o que é pela única coisa que não consegue ser: mãe. A luta do casal por um filho arrisca os alicerces da relação. Quinn não pode engravidar. Graham não é um candidato para adoção por conta de um erro do passado. O impasse os deixa parados no salão, no silêncio. A orquestra está em suspenso. Os dois parecem surdos para a música do amor de ambos. Será que é possível voltar a ouvir? A dançar? Ou será que vão descobrir a mais triste verdade de todas... que, às vezes, apenas amar não é o bastante?', 'Sim', '5 dias', '304', '304', '03/02/2023', '07/02/2023', '2023-08-02 04:16:38', '2023-08-02 04:17:20'),
(29, 8, '../img_livros/persuasao.png', 'Persuasão', 'Obra fundamental de Jane Austen (1775-1817), Persuasão é uma sátira social da Inglaterra do início do século XIX, mas, acima de tudo, uma história de amor contornada pela mágoa das oportunidades per¬didas. Com a sagacidade característica da autora, o romance gira em torno de Anne Elliot, que, aos 27 anos, tem poucas aspirações amorosas. Oito anos antes, tinha sido persuadida por sua amiga, Lady Russell, a romper o noivado com Frederick Wentworth, um belo oficial por quem era completamente apaixonada, mas que pertencia a outra classe social. Agora, o reaparecimento de Frederick faz com que Anne reflita sobre suas decisões do passado e contemple o futuro. Publicado em 1818, após a morte da escritora, o romance é considerado o mais bem-realizado e maduro de sua memorável carreira. Poucos escritores conseguiram transmitir as sutilezas e nuances de seu próprio meio social com a inteligência e perspicácia de Jane Austen. Uma das principais romancistas da literatura mundial, consagrou-se pela ironia presente em seus romances, repletos de diálogos afiados e que, publicados originalmente no século XIX, causam encantamento no público até hoje e já ganharam diversas adaptações para o cinema e a TV. Esta edição traz a clássica tradução de Luiza Lobo, que também assina a introdução do livro.', 'Sim', '19 dias', '224', '224', '09/02/2023', '27/02/2023', '2023-08-02 04:18:19', '2023-08-02 04:19:08'),
(30, 8, '../img_livros/bibioteca_da_meia_noite.jpg', 'A Biblioteca da Meia-Noite', 'No limiar entre a vida e a morte existe uma biblioteca. Cada livro vai dar a uma nova vida que podes escolher. O regresso de Matt Haig com uma fábula dos tempos modernos multipremiada. PRÉMIO GOODREADS PARA MELHOR LIVRO DE FICÇÃO Finalista dos British Book Awards para Melhor Livro de Ficção Autor bestseller New York Times, Sunday Times e Amazon Se pudesses escolher a melhor vida para viver, o que farias? No limiar entre a vida e a morte, depois de uma vida cheia de desgostos e carregada de remorsos, Nora Seed dá por si numa biblioteca onde o relógio marca sempre a meia-noite e as estantes estão repletas de livros que se estendem até perder de vista. Cada um desses livros oferece-lhe a hipótese de experimentar uma outra vida, de fazer novas escolhas, de corrigir erros, de perceber o que teria acontecido se tivesse escolhido um caminho diferente. As possibilidades são infinitas e vários horizontes se abrem à sua frente. Mas será que algum desses caminhos lhe proporciona uma vida mais perfeita do que aquela que conheceu? Na altura da escolha final, Nora terá de olhar para dentro de si mesma e decidir o que de facto lhe preenche a vida e o que faz com que valha a pena vivê-la. A Biblioteca da Meia-Noite transformou-se num bestseller a nível internacional, com um milhão de livros vendidos em todo o mundo. Os elogios da crítica: «Uma fábula belíssima, um Do Céu Caiu Uma Estrela dos tempos modernos. Incrivelmente intemporal, numa altura em que estamos todos encurralados num mundo que desejaríamos que fosse diferente.» — Jodi Picoult', 'Sim', '23 dias', '288', '288', '01/03/2023', '23/03/2023', '2023-08-02 04:23:41', '2023-08-02 04:24:30'),
(31, 8, '../img_livros/corte_de_espinhos_e_rosas2.png', 'Corte de espinhos e rosas - Corte de espinhos e rosas - vol. 1', 'Ela roubou uma vida. Agora deve pagar com o coração. Nesse misto de A Bela e A Fera e Game of Thrones, Sarah J. Maas cria um universo repleto de ação, intrigas e romance. Depois de anos sendo escravizados pelas fadas, os humanos conseguiram se libertar e coexistem com os seres místicos. Cerca de cinco séculos após a guerra que definiu o futuro das espécies, Feyre, filha de um casal de mercadores, é forçada a se tornar uma caçadora para ajudar a família. Após matar uma fada zoomórfica transformada em lobo, uma criatura bestial surge exigindo uma reparação. Arrastada para uma terra mágica e traiçoeira — que ela só conhecia através de lendas —, a jovem descobre que seu captor não é um animal, mas Tamlin, senhor da Corte Feérica da Primavera. À medida que ela descobre mais sobre este mundo onde a magia impera, seus sentimentos por Tamlin passam da mais pura hostilidade até uma paixão avassaladora. Enquanto isso, uma sinistra e antiga sombra avança sobre o mundo das fadas e Feyre deve provar seu amor para detê-la... ou Tamlin e seu povo estarão condenados.', 'não', '0 dias', '65', '434', '25/03/2023', NULL, '2023-08-02 04:26:42', '2023-08-02 04:27:14'),
(32, 8, '../img_livros/sorrisos_quebrados.png', 'Sorrisos Quebrados', 'É na escuridão que brilha o amor verdadeiro. Paola: Perante Deus, meu marido prometeu me amar. Cuidar de mim. Ser meu amigo. Perante todos, disse que me amava. Que seríamos felizes. Viveríamos para sempre juntos. Mentiu em tudo. Até que um dia ele me disse que me mataria. E não mentiu. A partir desse dia, vivi escondida no meu mundo, até André aparecer. André: Eu não procurava nada. Não queria ninguém. Não depois de tudo que vivera. Meu coração estava escondido na escuridão, até Paola surgir com suas cores, pintando minha vida. Sorrisos Quebrados é um romance de cores entre duas pessoas quebradas por relacionamentos passados. Uma história de superação dos próprios medos e de promessas.', 'Sim', '18 dias', '240', '240', '07/04/2023', '24/04/2023', '2023-08-02 04:28:21', '2023-08-02 04:29:03'),
(33, 8, '../img_livros/cidade_da_lua_crescente.png', 'Cidade da Lua Crescente - Casa de Terra e Sangue (Vol. 1) - Edição revista', 'A autora #1 do New York Times Sarah J. Maas lança sua novíssima série Cidade da Lua Crescente. Neste primeiro volume, Casa de terra e sangue, conhecemos a história da semifeérica Bryce Quinlan, que busca vingança em um mundo de fantasia contemporâneo repleto de magia, perigo e romance abrasador. Bryce Quinlan tinha a vida perfeita - trabalhava duro o dia todo e festejava noite adentro -, até que um demônio assassina alguns de seus melhores amigos, deixando-a destruída e mudando sua vida para sempre. Sem entender como sobreviveu ao ataque da besta, a semifeérica tenta superar a perda, com o consolo de que o culpado por conjurar o demônio está atrás das grades. Mas quando os crimes recomeçam, dois anos depois e com as mesmas características, Bryce se vê no meio de uma investigação que pode ajudá-la a vingar a morte dos amigos. Hunt Athalar é um notório anjo caído, agora escravizado pelos arcanjos que um dia tentou derrubar. Suas habilidades brutais e força incrível foram definidas para alcançar um único objetivo: assassinar – sem perguntas – os inimigos do seu chefe. Mas com um demônio causando estragos na cidade, ele ofereceu um acordo irresistível: ajudar Bryce a encontrar o assassino, e sua liberdade estará ao seu alcance. Enquanto Bryce e Hunt se aprofundam nas entranhas da Cidade da Lua Crescente, eles descobrem um poder sombrio que ameaça tudo e todos que amam, e encontram um no outro uma paixão ardente – que teria o poder de libertar os dois, se eles apenas a aceitassem. Com personagens inesquecíveis, romance ardente e um suspense eletrizante a cada virar de página, Casa de terra e sangue é o primeiro volume da nova série de fantasia da autora best-seller no 1 do New York Times, Sarah J. Maas. Com mais de 1 milhão de exemplares vendidos em todo o mundo, Sarah é um fenômeno. Vencedora de três prêmios literários em anos consecutivos, a autora possui uma legião de fãs apaixonados. Agora, estreia brilhantemente no universo da ficção new adult.', 'não', '0 dias', '0', '744', '29/04/2023', NULL, '2023-08-02 04:29:48', '2023-08-02 04:29:48'),
(34, 8, '../img_livros/e_assim_que_acaba.jpg', 'É Assim Que Acaba', 'Lily vive um romance manipulado e dependente de Ryle', 'Sim', '11 dias', '368', '368', '05/06/2023', '15/06/2023', '2023-08-02 04:32:33', '2023-08-02 13:05:42'),
(35, 8, '../img_livros/e_assim_que_comeca.jpg', 'É Assim Que Começa', 'Lily agora vive um romance com seu amor verdadeiro. Atlas', 'Sim', '8 dias', '336', '336', '16/06/2023', '23/06/2023', '2023-08-02 04:35:16', '2023-08-02 13:06:32'),
(36, 8, '../img_livros/o_lado_feio_do_amor.png', 'O lado feio do amor', 'O maior best-seller de Collen Hoover, autora das séries Slammed e Hopeless, chega ao Brasil Quando Tate Collins se muda para o apartamento de seu irmão, Corbin, a fim de se dedicar ao mestrado em enfermagem, não imaginava conhecer o lado feio do amor. Um relacionamento onde companheirismo e cumplicidade não são prioridades. E o sexo parece ser o único objetivo. Mas Miles Archer, piloto de avião, vizinho e melhor amigo de Corbin, sabe ser persuasivo... apesar da armadura emocional que usa para esconder um passado de dor. O que Miles e Tate sentem não é amor à primeira vista, mas uma atração incontrolável. Em pouco tempo não conseguem mais resistir e se entregam ao desejo. O rapaz impõe duas regras: sem perguntas sobre o passado e sem esperanças para o futuro. Será um relacionamento casual. Eles têm a sintonia perfeita. Tate prometeu não se apaixonar. Mas vai descobrir que nenhuma regra é capaz de controlar o amor e o desejo.', 'Sim', '14 dias', '336', '336', '25/06/2023', '08/07/2023', '2023-08-02 04:36:54', '2023-08-02 04:41:52'),
(37, 8, '../img_livros/as_mil_partes_do_meu_coracao.png', 'As mil partes do meu coração', 'Autora best-seller do New York Times aborda relacionamentos e transtornos mentais em uma narrativa que discute os limites do que é normal. Para Merit Voss, a cerca branca ao redor da sua casa é a única coisa normal quando o assunto é sua família, peculiar e cheia de segredos. Eles moram em uma antiga igreja, batizada de Dólar Voss. A mãe, curada de um câncer, mora no porão, e o pai e o restante da família, no andar de cima. Isso inclui sua nova esposa, a ex-enfermeira da ex-mulher, o pequeno Moby, fruto desse relacionamento, o irmão mais velho, Utah, e a gêmea idêntica de Merit, Honor. E, como se a casa não tivesse cheia o bastante, ainda chegam o excêntrico Luck e o misterioso Sagan. Mas Merit sente que é o oposto de todos ali. Além de colecionar troféus que não ganhou, Merit também coleciona segredos que sua família insiste em manter. E começa a acreditar que não seria uma grande perda se um dia ela desaparecesse. Mas, antes disso, a garota decide que é hora de revelar todas as verdades e obrigá-los a enfim encarar o que aconteceu. Mas seu plano não sai como o esperado e ela deve decidir se pode dar uma segunda chance não apenas à sua família, mas também a si mesma. As mil partes do meu coração mostra que nunca é tarde para perdoar e que não existe família perfeita, por mais branca que seja a cerca.', 'Sim', '13 dias', '336', '336', '20/07/2023', '02/08/2023', '2023-08-02 13:07:26', '2023-08-03 04:55:26'),
(38, 8, '../img_livros/novembro_9.png', 'Novembro 9', 'Sinopse Uma história de amor inesquecível entre um aspirante a escritor e sua musa improvável, da autora de Hopeless. Fallon conhece Ben, um aspirante a escritor, bem no dia da sua mudança de Los Angeles para Nova York. A química instantânea entre os dois faz com que passem o dia inteiro juntos – a vida atribulada de Fallon se torna uma grande inspiração para o romance que Ben pretende escrever.', 'Sim', '15 dias', '349', '349', '03/08/2023', '20/08/2023', '2023-08-03 04:57:20', '2023-08-20 16:51:37'),
(40, 1, 'public/img_livros/40.png', 'As mil partes do meu coração', 'Autora best-seller do New York Times aborda relacionamentos e transtornos mentais em uma narrativa que discute os limites do que é normal. Para Merit Voss, a cerca branca ao redor da sua casa é a única coisa normal quando o assunto é sua família, peculiar e cheia de segredos. Eles moram em uma antiga igreja, batizada de Dólar Voss. A mãe, curada de um câncer, mora no porão, e o pai e o restante da família, no andar de cima. Isso inclui sua nova esposa, a ex-enfermeira da ex-mulher, o pequeno Moby, fruto desse relacionamento, o irmão mais velho, Utah, e a gêmea idêntica de Merit, Honor. E, como se a casa não tivesse cheia o bastante, ainda chegam o excêntrico Luck e o misterioso Sagan. Mas Merit sente que é o oposto de todos ali. Além de colecionar troféus que não ganhou, Merit também coleciona segredos que sua família insiste em manter. E começa a acreditar que não seria uma grande perda se um dia ela desaparecesse. Mas, antes disso, a garota decide que é hora de revelar todas as verdades e obrigá-los a enfim encarar o que aconteceu. Mas seu plano não sai como o esperado e ela deve decidir se pode dar uma segunda chance não apenas à sua família, mas também a si mesma. As mil partes do meu coração mostra que nunca é tarde para perdoar e que não existe família perfeita, por mais branca que seja a cerca.', 'sim', '26 dias', '336', '336', '11/06/2023', '24/08/2023', '2023-08-12 03:02:03', '2023-08-25 02:16:14'),
(42, 1, 'public/img_livros/42.png', 'Boa garota, segredo mortal', 'PRESENTE DA TANIA - 18/08/2023 \r\n\r\nNa sequência do best-seller Manual de assassinato para boas garotas, um desaparecimento misterioso abala Little Kilton Um ano após a investigação obsessiva que reescreveu a história de sua pacata cidade, Pip acredita que seus dias de detetive amadora chegaram ao fim. Prometendo nunca mais se envolver no emaranhado de segredos de Little Kilton, a garota planeja lançar um podcast sobre a resolução do caso e voltar a ter uma vida normal. Até que algo terrível acontece, e ela precisa quebrar sua promessa. Jamie Reynolds, o irmão de um de seus melhores amigos, está desaparecido. Ele foi visto pela última vez no memorial dedicado a Andie Bell e Sal Singh, seis anos após o crime. Seria mera coincidência? Quando a polícia se recusa a agir, Pip decide voltar à ativa. Com a ajuda dos amigos, dos ouvintes do podcast e de Ravi, ela se lança em uma busca frenética para encontrar Jamie antes que seja tarde demais. Cada segundo conta, e só resta uma certeza: ninguém em Little Kilton é quem diz ser. Nessa trama afiada, os efeitos da primeira investigação de Pip se misturam com um novo mistério arrepiante. E ela está disposta a correr riscos ainda maiores em sua busca pela verdade. Na sequência de Manual de assassinato para boas garotas, Holly Jackson constrói mais um thriller surpreendente, profundo e impossível de largar.', 'sim', '34 dias', '466', '466', '18/08/2023', '21/09/2023', '2023-08-19 02:37:58', '2023-09-22 03:37:00'),
(43, 8, '../img_livros/ate_o_verao_terminar.png', 'Até o verão terminar', 'Uma vida de dor e abandono fizeram de Beyah uma pessoa cética, desconfiada e boa em guardar segredos. Mas, até o verão terminar, ela terá que rever tudo o que acredita. Da mesma autora dos sucessos É assim que acaba, Layla e Verity. Filha de uma mãe problemática e um pai ausente, Beyah precisou aprender a se virar sozinha desde pequena. Sua vida foi trilhada com muitas decepeções. Mas ela está prestes a mudar a sua sorte graças a si mesma, e a mais ninguém, por conta da bolsa de estudos que ganhou para estudar em uma boa universidade. Apenas dois curtos meses separam o tão sonhado futuro do passado que tanto deseja deixar para trás. Mas uma reviravolta faz Beyah perder até mesmo a casa em que mora. Sem opção, ela recorre ao último recurso que tem e precisará passar o resto do verão na casa de praia do pai que mal conhece, da nova esposa e da filha dela que nem ao menos ouvira falar. O plano de Beyah é se manter quase invisível até poder ir para a faculdade. Mas o vizinho da casa ao lado torna tudo muito mais complicado. Afinal, é difícil ignorar o rico, bonito e misterioso Samson. Os dois parecem não ter nada em comum. Ela viveu uma vida sem dinheiro ou amor enquanto ele tem uma família rica e privilegiada. Mas no olhar dele vive uma tristeza que apenas quem também a carrega dentro de si consegue reconhecer. E isso os torna irresístiveis um para o outro. Sem terem como fugir da atração que sentem, Beyah e Samson resolvem se dar uma chance, mas apenas até o verão terminar. Uma história de amor, recomeços, despedidas e reencontros. \"Desde 2015, Hoover conquista os corações dos leitores de romance de todo o mundo com suas histórias contemporâneas sobre os altos e baixos do amor verdadeiro.\" — Goodreads', 'Sim', '21 dias', '336', '336', '21/08/2023', '30/08/2023', '2023-08-22 03:19:08', '2023-08-30 23:34:56'),
(44, 8, '../img_livros/layla.png', 'Layla', '“Quando Leeds conhece Layla, ele está convencido de que passará o resto de sua vida com ela – até que um ataque inesperado deixa Layla lutando por sua vida. Depois de semanas no hospital, Layla se recupera fisicamente, mas as cicatrizes emocionais e mentais foram alteradas. a mulher por quem Leeds se apaixonou. Para colocar seu relacionamento de volta nos trilhos, Leeds leva Layla para a pousada onde se conheceram. Assim que chegam, o comportamento de Layla toma um rumo bizarro. E esse é apenas um dos muitas ocorrências inexplicáveis.\"--', 'não', '0 dias', '0', '304', '31/08/2023', NULL, '2023-09-03 21:25:55', '2023-09-03 21:25:55'),
(45, 9, 'http://books.google.com/books/content?id=5lyKMOxNFj4C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api', 'Conan the Triumphant', 'conan', 'não', '0 dias', '0', '322', '09/09/2023', NULL, '2023-09-05 23:01:36', '2023-09-05 23:01:36'),
(46, 1, '../img_livros/layla.png', 'Layla', 'Em uma mistura de thriller sobrenatural e romance, Layla promete prender e surpreender o leitor até a última página. Da mesma autora de Verity. Quando Leeds conhece Layla, ele está convencido de que passará o resto de sua vida com ela… Ela é espontânea, divertida, e a vida ao seu lado é fácil e tranquila', 'sim', '8 dias', '366', '366', '22/09/2023', '28/09/2023', '2023-09-23 02:56:36', '2023-09-30 16:55:43'),
(47, 8, 'public/img_livros/42.png', 'Boa garota, segredo mortal', 'Na sequência do best-seller Manual de assassinato para boas garotas, um desaparecimento misterioso abala Little Kilton Um ano após a investigação obsessiva que reescreveu a história de sua pacata cidade, Pip acredita que seus dias de detetive amadora chegaram ao fim. Prometendo nunca mais se envolver no emaranhado de segredos de Little Kilton, a garota planeja lançar um podcast sobre a resolução do caso e voltar a ter uma vida normal. Até que algo terrível acontece, e ela precisa quebrar sua promessa. Jamie Reynolds, o irmão de um de seus melhores amigos, está desaparecido. Ele foi visto pela última vez no memorial dedicado a Andie Bell e Sal Singh, seis anos após o crime. Seria mera coincidência? Quando a polícia se recusa a agir, Pip decide voltar à ativa. Com a ajuda dos amigos, dos ouvintes do podcast e de Ravi, ela se lança em uma busca frenética para encontrar Jamie antes que seja tarde demais. Cada segundo conta, e só resta uma certeza: ninguém em Little Kilton é quem diz ser. Nessa trama afiada, os efeitos da primeira investigação de Pip se misturam com um novo mistério arrepiante. E ela está disposta a correr riscos ainda maiores em sua busca pela verdade. Na sequência de Manual de assassinato para boas garotas, Holly Jackson constrói mais um thriller surpreendente, profundo e impossível de largar.', 'sim', '7 dias', '466', '466', '22/09/2023', '28/09/2023', '2023-09-24 04:03:12', '2023-09-30 23:14:48'),
(48, 1, '../img_livros/ate_o_verao_terminar.png', 'Até o verão terminar', 'Uma vida de dor e abandono fizeram de Beyah uma pessoa cética, desconfiada e boa em guardar segredos. Mas, até o verão terminar, ela terá que rever tudo o que acredita. Da mesma autora dos sucessos É assim que acaba, Layla e Verity. Filha de uma mãe problemática e um pai ausente, Beyah precisou aprender a se virar sozinha desde pequena. Sua vida foi trilhada com muitas decepeções. Mas ela está prestes a mudar a sua sorte graças a si mesma, e a mais ninguém, por conta da bolsa de estudos que ganhou para estudar em uma boa universidade. Apenas dois curtos meses separam o tão sonhado futuro do passado que tanto deseja deixar para trás. Mas uma reviravolta faz Beyah perder até mesmo a casa em que mora. Sem opção, ela recorre ao último recurso que tem e precisará passar o resto do verão na casa de praia do pai que mal conhece, da nova esposa e da filha dela que nem ao menos ouvira falar. O plano de Beyah é se manter quase invisível até poder ir para a faculdade. Mas o vizinho da casa ao lado torna tudo muito mais complicado. Afinal, é difícil ignorar o rico, bonito e misterioso Samson. Os dois parecem não ter nada em comum. Ela viveu uma vida sem dinheiro ou amor enquanto ele tem uma família rica e privilegiada. Mas no olhar dele vive uma tristeza que apenas quem também a carrega dentro de si consegue reconhecer. E isso os torna irresístiveis um para o outro. Sem terem como fugir da atração que sentem, Beyah e Samson resolvem se dar uma chance, mas apenas até o verão terminar. Uma história de amor, recomeços, despedidas e reencontros. \"Desde 2015, Hoover conquista os corações dos leitores de romance de todo o mundo com suas histórias contemporâneas sobre os altos e baixos do amor verdadeiro.\" — Goodreads', 'não', '0 dias', '0', '336', '29/09/23', NULL, '2023-09-30 16:57:30', '2023-09-30 16:57:30'),
(49, 8, '../img_livros/uma_segunda_chance.jpg', 'Uma Segunda Chance', '....', 'não', '0 dias', '0', NULL, '02/10/2023', NULL, '2023-10-03 23:34:31', '2023-10-03 23:34:31');

-- --------------------------------------------------------

--
-- Estrutura para tabela `users`
--

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `primary_color` varchar(20) NOT NULL DEFAULT '#5bb4ff',
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Despejando dados para a tabela `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `primary_color`, `remember_token`, `created_at`, `updated_at`) VALUES
(1, 'João Enrique', 'joao@gmail.com', NULL, '$2y$10$xl2bfSpBMAa8C1Fpf72B3ezDF3KokLmkAf/wfCj6kyt3PMK.YaJuu', '#5bb4ff', 'hl2PW6g1h25RhyuM0dkI6ceNXF31QaHoQ8XJ9pyGjQIFjvUTMdnHHXzUA6ER', '2023-06-02 06:11:30', '2023-06-11 01:36:28'),
(3, 'Elaine Cristina Alves De Souza', 'elaine@gmail.com', NULL, '$2y$10$67pSzwpsRZN7EuNjV85FU.t3fl.BqQiPgpQ/KrZ6s/68WW96f7.Py', '#5bb4ff', 'hFWkDVDxgxyxHQRl3eOAjmbi52XlRLOhFZbL5luFYbY697AZD8GLi8ppTfgh', '2023-06-03 07:44:58', '2023-06-05 06:30:09'),
(4, 'Adelson Barbosa  Santos', 'adelson@gmail.com', NULL, '$2y$10$ZnZ7VNRgPqBVGUNZf7TWV.yu1IE0H.JBnb7vv36nhtI51GeuW9lGm', '#5bb4ff', '9551EcRfE7kbaIUH25boyl7mmsHICfVhELm1msMJMVaFXZKhSEr9idSqz351', '2023-06-03 07:56:51', '2023-06-03 07:56:51'),
(5, 'João Enrique Barbosa Santos Alves', 'jebsantosalves@gmail.com', NULL, '$2y$10$vrzkQ15d0vAhiFX1Yt2tIO1TyC6CQ/9VAL91a1tv0CS.RzqXjtpHu', '#5bb4ff', NULL, '2023-06-07 03:01:59', '2023-06-07 03:01:59'),
(7, 'Sarah Janadozza', 'sarah@gmail.com', NULL, '$2y$10$vGneUCoesxl8yz8xZ9DTGeM/H1xpMErcOfiAwwQC5iUqSL/Bns4hO', '#5bb4ff', '093PGx0Zi3vzmZU43iIPu2GWFosGYFAc6sG1VmFVxSIjX4wwNKDk4UOSKAnc', '2023-06-20 20:59:05', '2023-06-20 20:59:05'),
(8, 'Tânia Carol', 'tania.fernandez@gmail', NULL, '$2y$10$awUDpMQtNw0cKzdtlYZFg.BNEp44Vj51FHTAMH8F6bD4l6sMMKwP6', '#5bb4ff', NULL, '2023-08-02 03:11:07', '2023-08-02 03:11:07'),
(9, 'paulo', 'paulovini064@gmail.com', NULL, '$2y$10$18VT8Nu5p6SQzlHaN03.SOLX5wGpqaY1XTJQoiUQaSKf1ZJsaLUo2', '#5bb4ff', NULL, '2023-09-05 22:59:31', '2023-09-05 22:59:31');

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `admins`
--
ALTER TABLE `admins`
  ADD PRIMARY KEY (`id`),
  ADD KEY `admins_idusuario_foreign` (`idUsuario`);

--
-- Índices de tabela `livros`
--
ALTER TABLE `livros`
  ADD PRIMARY KEY (`id_livro`),
  ADD KEY `livros_id_usuario_foreign` (`id_usuario`);

--
-- Índices de tabela `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `admins`
--
ALTER TABLE `admins`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT de tabela `livros`
--
ALTER TABLE `livros`
  MODIFY `id_livro` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=50;

--
-- AUTO_INCREMENT de tabela `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- Restrições para tabelas despejadas
--

--
-- Restrições para tabelas `admins`
--
ALTER TABLE `admins`
  ADD CONSTRAINT `admins_idusuario_foreign` FOREIGN KEY (`idUsuario`) REFERENCES `users` (`id`);

--
-- Restrições para tabelas `livros`
--
ALTER TABLE `livros`
  ADD CONSTRAINT `livros_id_usuario_foreign` FOREIGN KEY (`id_usuario`) REFERENCES `users` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
